# region Kinect Control
KINECT_MAX_CHECKS_CONNECTION = 5
KINECT_SECONDS_BETWEEN_CHECK_CONNECTION = 3
# endregion

# region Window Control
WINDOW_MAX_RETRIES_CREATION = 3
WINDOW_SECONDS_BETWEEN_CREATIONS = 1
# endregion